# Generated by Django 4.2 on 2024-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
